config/routes.rb
Rails.application.routes.draw do
  # authenticated :user do
  #   root :to => 'redirections#index', :as => :authenticated_root
  # end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :user, only: [:show]

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end
end

app/views/menus/_footer.html.erb
<div id="footer_menu">
<ul>
  <% unless user_signed_in? && User.omniauth_providers && User.omniauth_providers.include?(:auth_man) %>
  <li><%= link_to t('users.local_login'), new_user_session_path %></li>
  <% end %>
</ul>
</div>

app/views/menus/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t('application.name'), root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <% if current_user.has_role?(:admin) %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('administration.administration') %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('administration.users'), admin_users_path %></li>
                  </ul>
                </li>
            <% end %>
            <li class="divider-vertical"></li>
            <%= render 'menus/my_account', :user => current_user, :my_account_path => user_path, :gravatar_url =>  current_user.gravatar_url(:size => 20) %>
        <% else %>
            <%= render 'devise/menu/login_items' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/menus/_my_account.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= show_gravatar(APP_CONFIG) ? (image_tag(gravatar_url ? gravatar_url : user.gravatar_url(:size => 20))) : user.full_name_comma %> <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <% if show_gravatar(APP_CONFIG) %>
        <li class="navbar-text"><%= "Welcome, #{user.fname}!" %></li>
        <li class="divider"></li>
    <% end %>
    <li><%= link_to t('look_and_feel.account.my_account'), my_account_path ? my_account_path : user_path %></li>
    <li class="divider"></li>
    <%= render 'devise/menu/login_items' %>
  </ul>
</li>