config/routes.rb
Rails.application.routes.draw do
  # authenticated :user do
  #   root :to => 'redirections#index', :as => :authenticated_root
  # end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :user, only: [:show]

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  devise :omniauthable, :omniauth_providers => [:auth_man]

  include RoleModel
  roles_attribute :roles_mask
  roles :admin, :user

  include Gravtastic
  #gravtastic :secure => (AppConfig.get(%w(user_profiles secure), APP_CONFIG) ? AppConfig.get(%w(user_profiles secure), APP_CONFIG) : false)
  gravtastic :secure => false

  before_create :set_default_roles

  def self.from_omniauth(auth)
    user_return = where(provider: auth.provider, uid: auth.uid).first

    unless user_return
      user = User.new(
          :email        => auth.info.email,
          :password     => Devise.friendly_token[0,20],
          :fname        => auth.info.fname,
          :lname        => auth.info.lname,
          :time_zone    => auth.info.time_zone,
      )

      user.uid      = auth.uid
      user.provider = auth.provider

      user.skip_confirmation!
      user.save

      user_return = user
    end

    user_return.sync_with_omniauth(auth)

    user_return
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.auth_man_data'] && session['devise.auth_man_data']['extra']['raw_info']
        user.email      = data['email'] if user.email.blank?
        user.fname      = data['fname'] if user.fname.blank?
        user.lname      = data['lname'] if user.lname.blank?
        user.time_zone  = data['time_zone'] if user.time_zone.blank?
      end
    end
  end

  def sync_with_omniauth(auth)
    unless auth.info.fname == self.fname && auth.info.lname == self.lname && auth.info.time_zone == self.time_zone
      self.fname      = auth.info.fname
      self.lname      = auth.info.lname
      self.time_zone  = auth.info.time_zone

      self.save
    end
  end

  def full_name
    "#{self.fname} #{self.lname}"
  end

  def full_name_comma
    "#{self.lname}, #{self.fname}"
  end

  private
  def set_default_roles
    self.roles << :regular
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    user_account_params = user_params

    @user = User.new(user_account_params)

    if @user.save
      flash[:notice] = t('users.created_user')
      redirect_to admin_user_path(@user)
    else
      render :action => 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    user_account_params = user_params

    if user_account_params[:password].blank?
      user_account_params.delete(:password)
      user_account_params.delete(:password_confirmation)
    end

    if @user.update_attributes(user_account_params)
      flash[:notice] = t('users.updated_user')
      redirect_to admin_users_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = t('users.deleted_user')
      redirect_to admin_users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :time_zone, :fname, :lname, roles: [], application_ids: [])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def auth_man
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      session['devise_omniauth_myaccount'] = request.env['omniauth.auth'].info.my_account
      session['devise_omniauth_enable_gravatar'] = request.env['omniauth.auth'].info.enable_gravatar
      session['devise_login_type'] = :omniauth

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => 'AuthMan') if is_navigational_format?
    else
      raise Exception.new('Failed to create or find user.')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
      @user ||= User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :time_zone, :roles_mask, :provider, :uid)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, :url => resource_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :fname, t('users.first_name') %><br />
      <%= f.text_field :fname %>
    </div>
    <div class="field">
      <%= f.label :lname, t('users.last_name') %><br />
      <%= f.text_field :lname %>
    </div>
    <div class="field">
      <%= f.label :roles %>
      <ul>
        <% User.valid_roles.each do |role| %>
            <li id="role_<%= role %>"><%= role %><%= check_box_tag 'user[roles][]', role, @user.has_role?(role) %></li>
        <% end %>
      </ul>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t('general.editing') % t('users.users') %></h1>

<%= render 'form', :resource_path => admin_user_path %>

app/views/admin/users/index.html.erb
<h1><%= t('general.listing') % t('users.users') %>
  <span class='actions'>
        <% if user_signed_in? %>
          <%= link_to 'New', new_admin_user_path, :id => 'new_user_link' %>
        <% end  %>
    </span>
</h1>

<table id='index_table' class='data_table'>
  <thead>
      <tr>
        <th><%= t('users.email_address') %></th>
        <th><%= t('users.administrator') %></th>
        <th><%= t('general.tables.actions') %></th>
      </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email ? user.email : user.unconfirmed_email, admin_user_path(user) %></td>
        <td><%= user.has_role?(:admin) ? t('general.yes') : t('general.no') %></td>
        <td>
          <%= link_to t('general.edit'), edit_admin_user_path(user) %>
          <% if user != current_user %>
            <%= link_to t('general.destroy'), admin_user_path(user), :confirm => t('general.are_you_sure'), :method => :delete %></td>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1><%= t('general.new') % t('users.user') %></h1>

<%= render 'form', :resource_path => admin_users_path %>
<br />
<br />
<%= link_to t('general.back'), :back %>

app/views/admin/users/show.html.erb
<h1><%= @user.email ? @user.email.upcase : @user.unconfirmed_email.upcase %></h1>
<div class='model_info'>
  <h3><%= t('users.attributes') %>:</h3>
  <table id='user_attributes'>
    <tr>
      <td><%= t('users.confirmed_on') %></td>
      <td><%= @user.confirmed_at ? @user.confirmed_at.to_formatted_s(:long_ordinal) : t('users.not_confirmed') %></td>
    </tr>
    <tr>
      <td><%= t('users.administrator') %></td>
      <td><%= @user.has_role?(:admin) ? t('general.yes') : t('general.no') %></td>
    </tr>
  </table>
</div>
<br/><br/><br/>

<%= link_to t('general.back'), admin_users_path %>